.gitignore, .travis.yml, Makefile, README.md, build_scripts/deploy.sh
In continue to #29 
- Instruct Travis CI to deploy compiled plugins (with stable version of SDK)
to `build` branch every time `master` branch is modified. Pull requests
don't trigger this action.
`$ GH_TOKEN=<your token> make compile pack deploy` is what is done behind the
scenes
- Using `./build/` directory for builds (ignored by git)
- Only `./updated/` directory is deployed
=> Introduce auto deployment

.travis.yml
Since `dev` and `stable` compilations were separated and `dev` compilation is allowed to fail, Travis can mark build as finished as soon as `stable` compilation is completed.
After this PR is merged, Travis build should be ~2 times faster than before.
=> Optimize travis build time by not waiting for dev compilation

.travis.yml
- Use Travis `deploy` directive instead of `after_success`
`deploy` is more suitable as it's definition is more readable
in `.travis.yml` configuration file + it doesn't run on PR
and forks by default
=> Simplify Travis CI deployment

.travis.yml, Makefile, build_scripts/deploy.sh
Fixed the issues with #59 
- Use Travis `deploy` directive instead of `after_success`
`deploy` is more suitable as it's definition is more readable
in `.travis.yml` configuration file + it doesn't run on PR
and forks by default
- Add `.git` extension to repo URL. According to my tests, git command
within Travis CI failed to find repository without it
- Print error & fail build in Travis CI if deployment fails
- Remove encrypted `GH_TOKEN` environment variable from code and keep it in
Travis CI repo settings instead.
Please insert your GitHub OAuth token inside Travis CI settings before merging this.
=> Simplify Travis CI deployment (2nd try)

addons/sourcemod/scripting/nd_universal_translator.sp, addons/sourcemod/scripting/ndpc/building_requests.sp, addons/sourcemod/scripting/ndpc/capture_requests.sp, addons/sourcemod/scripting/ndpc/stock_functions.sp
- Add a lot of commenting to the building request module.
- Use a new wrapper function to clarify the code further.
- Log what a client said every-time no translation keyword is found.
=> Improve translation plugin

addons/sourcemod/scripting/nd_universal_translator.sp, addons/sourcemod/scripting/ndpc/features/commander_lang.sp, addons/sourcemod/scripting/ndpc/features/file_logging.sp, addons/sourcemod/scripting/ndpc/features/team_lang.sp, addons/sourcemod/scripting/ndpc/reg_functions.sp, addons/sourcemod/scripting/ndpc/requests/build_req.sp, addons/sourcemod/scripting/ndpc/requests/capture_req.sp, addons/sourcemod/scripting/ndpc/requests/repair_req.sp, addons/sourcemod/scripting/ndpc/requests/research_req.sp, updater/nd_universal_translator/translations/es/nd_universal_translator.phrases.txt, updater/nd_universal_translator/translations/nd_universal_translator.phrases.txt, updater/nd_universal_translator/translations/ru/nd_universal_translator.phrases.txt
- Use colors.inc for chat colours.
- Move player name outside of phrases and to start of translation message.
- Light the player name up blue or red depending on the team
=> Improve UT printouts

addons/sourcemod/scripting/ndpc/reg_functions.sp, addons/sourcemod/scripting/ndpc/requests/build_req.sp, addons/sourcemod/scripting/ndpc/requests/capture_req.sp, addons/sourcemod/scripting/ndpc/requests/repair_req.sp, addons/sourcemod/scripting/ndpc/requests/research_req.sp
- Use trans string and print request functions.
- Don't create new voids for each print request anymore.
=> Majorly Cleanup UT Code

addons/sourcemod/scripting/nd_deadweights.sp, addons/sourcemod/scripting/nd_exp_checker.sp, addons/sourcemod/scripting/nd_gameme_skill.sp, addons/sourcemod/scripting/nd_player_warnings.sp, addons/sourcemod/scripting/sbchecker.sp, addons/sourcemod/scripting/votemute_p.sp
- This fixes translation errors, when the target is unable to be found.
=> Load common translations for find-target plugins

addons/sourcemod/scripting/include/nd_breakdown.inc, addons/sourcemod/scripting/nd_team_breakdown.sp, addons/sourcemod/scripting/nd_unit_limit.sp
- Use Redstone team count natives (more abstract)
- Use single function instead of multiple to get unit counts.
=> Setup new troop count version

addons/sourcemod/scripting/nd_rockthevote.sp
- Increase to 51% from 40% of votes to change map after 7m, on maps which are unpopular.
=> Prevent RTV abuse when losing

addons/sourcemod/scripting/include/nd_com_eng.inc, addons/sourcemod/scripting/nd_com_engine.sp, addons/sourcemod/scripting/nd_commander_checklist.sp
- Add ND_EnteredCommanderMode() native.
- Reset commander engine variables on map end, in case the round end event is bypassed.
- Change type in chat requirement from being in commander mode to entering it once.
=> Improve commander checklist plugin

addons/sourcemod/scripting/nd_bot_feat/modulus_quota.sp, addons/sourcemod/scripting/nd_bot_features.sp, addons/sourcemod/scripting/nd_managed_slots.sp
- Use new nd_maps.inc version to do some house cleaning
- Silo is fixed, so disable bots normally at 8 players now.
- Use actual client connect to decide of players can connect.
- Boost server slots on two overbalance instead of three.
- Make server slot boosting work properly with the reserved pool.
=> Improve nd_bot_features

addons/sourcemod/scripting/include/smlib/math.inc, addons/sourcemod/scripting/nd_player_skill.sp, addons/sourcemod/scripting/nd_ply_skill/prediction.sp, addons/sourcemod/scripting/nd_ply_skill/skill_calc.sp
- Reduce the overhead in calculating player and commander skill.
- Make it work better by fixing a few minor bugs with skill prediction.
- Round up in multiples of 5 bellow 30 instead of 20 for commander skill.
=> Optimize player skill math calculations

addons/sourcemod/scripting/nd_team_pick/commands.sp, addons/sourcemod/scripting/nd_team_picking.sp
- Reset plugin state back to default to fix bugs with various things like team-locking.
=> Reload team-picker on map change

addons/sourcemod/scripting/nd_slots/thresholds.sp
- Limit max server slots to 28 from 30 due to server hosting changes.
- Change regular medium slots from 28 to 26.
- Reclassify metro and silo as medium maps due to added ternary scaling.
- Increase medium map server slot min from 24 to 26.
=> Improve server slot config

addons/sourcemod/scripting/include/nd_warmup.inc, addons/sourcemod/scripting/nd_commander_actions.sp, addons/sourcemod/scripting/nd_rockthevote.sp, addons/sourcemod/scripting/nd_warmup.sp
- Rework warmup plugin to better check if team-pick is running.
- Restrict access to commander demote & promote to warmup only (for non-root clients)
- Restrict access to team-change commands to warmup only (for non-root clients)
=> Restrict event-hoster access to commands

addons/sourcemod/scripting/nd_pull_bot.sp, addons/sourcemod/scripting/nd_pull_bot/ground_check.sp, addons/sourcemod/scripting/nd_pull_bot/move_bot.sp, updater/nd_pull_bot/translations/nd_pull_bot.phrases.txt
- Add 8 second cooldown for using !PullBot
- Default ground_check to disabled if stype becomes unavailable.
- Increase ground check delay from 3s to 8s, so bots can capture resources.
- Use convars to control distance & delay variables. (instead of hard-coding)
- Add translation support to bot pull messages.
- Display a message when no bot is found in the cross-hair
- Enhance message of bot being too far away, by displaying units.
=> Improve pull bot plugin

addons/sourcemod/scripting/nd_team_breakdown.sp
- Check if the round is started each player death, instead of unhooking the event on round end.
=> Fix nd_team_breakdown hook errors

addons/sourcemod/scripting/nd_suicide_controls.sp
- Change from standard 6s delay to ranged 7-12s delay.
- Double probability of min and max to make more unpredictable.
- Add convars to control min and max values.
- Add convar to try number of retrys for min/max values.
=> Improve sucide delays

addons/sourcemod/scripting/nd_commander_demote.sp
- Use commander engine wrapper to detect bunker entry, instead of embedded check.
- Don't allow a client to re-apply for commander, after being vote demoted.
- Fix the variable resetting on the plugin to work with round resets.
=> Improve commander demote plugin

addons/sourcemod/scripting/nd_damage/convars.sp, addons/sourcemod/scripting/nd_damage/damage_events.sp, addons/sourcemod/scripting/nd_damage_mult.sp
- Patch an exploit causing siege weapons and grenade launchers to deal RED intended damage.
This will result in weapons dealing the intended damage to structures, which is up to 40% less.
- Increase GL structure damage to bunker by 20%, assembler by 10%, ft/sonic turrets 15%, spawns 20%.
These values are exactly half the exploit levels, that were previously being implemented. 
They include removal of buildings that are too weak: armory, radar, artillery, power plant.
=> Fix Structure Damage Exploit

addons/sourcemod/scripting/nd_damage/convars.sp, addons/sourcemod/scripting/nd_damage/damage_events.sp
- Separate into three different config files by value to reduce scrolling.
- Automatically clean the configuration files to remove housekeeping.
=> Rework damage ConVars with cleaner configurations

addons/sourcemod/scripting/nd_damage/damage_events.sp, addons/sourcemod/scripting/nd_damage_mult.sp
- Global float arrays must be assigned to a local variable first, as a work around to prevent server crashes.
- More information located here: https://github.com/alliedmodders/sourcemod/issues/800
=> Fix server crash exploit

addons/sourcemod/scripting/include/autoexecconfig.inc, addons/sourcemod/scripting/nd_damage/convars.sp, addons/sourcemod/scripting/nd_pull_bot.sp
- Fix string typo with bot pull delay
- Use AutoExecConfig wrapper to update cfg files.
=> Fix typo causing wrong bot pull delay

addons/sourcemod/scripting/nd_team_pick/picking_process.sp, addons/sourcemod/scripting/nd_team_pick/picking_timer.sp, addons/sourcemod/scripting/nd_team_pick/start_picking.sp, addons/sourcemod/scripting/nd_team_picking.sp
- This process is automated now. Manual allows commanders to exploit an early finish by sending cancel.
=> Remove manual team-pick finish

addons/sourcemod/scripting/nd_gameme_skill.sp, addons/sourcemod/scripting/nd_gskill/gameme/kill_stats.sp
- The max hpk was reducing new level 80's to 64, before that stat had enough time to develop.
=> Fix regression with skill base modifications

addons/sourcemod/scripting/include/nd_swgm.inc, addons/sourcemod/scripting/nd_advertise.sp, addons/sourcemod/scripting/nd_grenade_trails_deux.sp, addons/sourcemod/scripting/nd_trails/clientprefs.sp, updater/nd_translation_updater/translations/nd_common.phrases.txt
- Only display steam group advertisements for people not in the steam group
- Require players to join the RedstoneND steam group to disable server adverts.
- Require players to join the RedstoneND steam group to use grenade trails.
=> Integrate steam group into server

addons/sourcemod/scripting/nd_commander_chair.sp
- Fix late loading support when the plugin is reloaded middle match.
- Fix operator not properly checking the minimum the player count,
- Set 15s commander selection time with greater than min players.
- Set 30s commander selection time with less than min players.
=> Improve nd_commander_chair plugin

addons/sourcemod/scripting/include/nd_rounds.inc, addons/sourcemod/scripting/nd_commander_chair.sp, addons/sourcemod/scripting/nd_round_engine.sp, addons/sourcemod/scripting/nd_round_start.sp
- Remove dead forwards that do not perform any actions.
- Fire a forward before performing a normal round start.
- Fix a bug where commander election times must be set before round start.
=> Improve Round Engine

addons/sourcemod/scripting/nd_commander_chair.sp, updater/nd_commander_chair/translations/nd_commander_chair.phrases.txt
- Set two delays for entering the chair: 120s after round start and 60s after promotion. If one team doesn't have a commander, when the threshold is meant.
- Only notify commanders with messages from this plugin. Contacting other players in unnecessary.
- Resolve multiple syntax errors from the previous version, not catch by the compiler.
- Update phrases file to reflect the new shorter and less complicated phrases.
=> Improve Chair Block Feature

addons/sourcemod/scripting/nd_commander_chair.sp
- Add second check to determine to if both have a commander.
- Mark handles as invalid after closing them, in case there's an error reusing them.
=> Attempt to fix commander chair plugin

addons/sourcemod/scripting/nd_bot_features.sp
- Simplify code and resolve multiple bugs by setting mp_limitteams at round start,
- Raise update to delay to 0.5s when a client team is set. Attempt to resolve bug with bots not filling.
=> Simplify bot features & resolve multiple bugs

addons/sourcemod/scripting/nd_bot_feat/convars.sp, addons/sourcemod/scripting/nd_bot_feat/modulus_quota.sp, addons/sourcemod/scripting/nd_bot_features.sp
- Fix a regression with the bot filler quota not calculating the right number.
- Remove default argument from the bot filler quota function to prevent future regressions.
- Add ConVars to control the shut of bot modulus quota based on individual team counts.
- Adjust bot modulus quota to shut-off during most scenarios, where it could benefit the stacked team.
=> Improve Bot Features

addons/sourcemod/scripting/nd_commander_chair.sp
- Separate round start and after promotion chair wait thresholds for increased accuracy.
- Wait for 3 players on each team after promotion, instead of 8 players total on any team.
=> Improve Commander Chair Blocks

addons/sourcemod/scripting/nd_bot_features.sp
- Fix an issue causing the team with more skill to receive extra bots.
- Use getStackedTeam() wrapper function from nd_stocks.inc.
=> Fix Bot Features

addons/sourcemod/scripting/include/nd_transport_eng.inc, addons/sourcemod/scripting/nd_bot_features.sp, addons/sourcemod/scripting/nd_transport_engine.sp
- Add force player spawn support to nd_transport_engine.
- Add refresh spawn location support to nd_transport_engine.
- Forcefully spawn bots 8s after switch them, to fix spawn bugs.
=> Spawn bots after switching team

addons/sourcemod/scripting/nd_timelimit.sp
- Add 30m to time limit when commander skill is less than 15. And the time limit resumes late game.
- Use the autoexeconfig wrapper to create the plugin convars. Updates existing configuration files.
=> Improve time limit features

addons/sourcemod/scripting/include/nd_teampick.inc, addons/sourcemod/scripting/nd_team_pick/natives.sp, addons/sourcemod/scripting/nd_timelimit.sp
- Add native to team picker to see who the team captains are.
- Allow the time limit to be changed in the first 3m for rookie commanders.
=> Improve timelimit features

addons/sourcemod/scripting/include/nd_print.inc, addons/sourcemod/scripting/nd_damage/convars.sp, addons/sourcemod/scripting/nd_damage/damage_events.sp, addons/sourcemod/scripting/nd_damage_mult.sp, updater/nd_damage_mult/translations/nd_damage_mult.phrases.txt
- Add GL damage increases of 3%, 6% and 9% for Infantry boost.
- Move weapon damage increase values to console (to save space).
- Display GL damage increases in console. Add new stock functions.
=> Improve damage multipliers

addons/sourcemod/scripting/include/nd_classes.inc, addons/sourcemod/scripting/nd_player_speed.sp, updater/nd_player_speed/translations/nd_player_speed.phrases.txt
- Added 1%, 2%, 3% assault movement speed increases to Infantry Boost research.
- Moved movement speed increase values to console after research. (keep chat tidy)
=> Add movement speed increases for assaults

updater/nd_player_tips/translations/nd_player_tips.phrases.txt
As discussed on steam IM, 
I have added warning that Prime has been lost, a Bunker health warning, an extreme bunker health warning, 
And an average team health warning, but this one is ... needs some thought.
=> Add new triggered player tips

addons/sourcemod/scripting/nd_res_spawn/alpha.sp, addons/sourcemod/scripting/nd_res_spawn/commands.sp, addons/sourcemod/scripting/nd_resource_spawner.sp
- Deplete tertiary on spawn if prime is depleted.
- Don't always deplete with less than 12 players. We're going to deplete prime instead.
- Cleanup Convars
=> Improve Resource Spawner

addons/sourcemod/scripting/nd_offmap_fixes.sp
this fixed the conflict with shared named with arrays being called hax as there was no standardisation
=> renamed admirals variable to hax2

addons/sourcemod/scripting/nd_save_basespawn.sp
Ensures the commander cannot sell their last remaining base spawn powered by their command bunker. This prevents commanders from griefing by selling all base spawns and then destroying the power-grid to render the last remaining spawn outside of the base useless. Additional admin action upon detection is possible but not recommended due to edge cases where it is advantageous to move base spawns and commander may not be griefing. The action is logged which allows later administrative review.
=> Prevents commander griefing with spawns

addons/sourcemod/scripting/nd_build_restrict.sp
Uses consistent in-game communication to commander as other errors - provides an audible indicator with a denied sound as well as utilizes the commander-specific error field for more accessible messaging to the commander
=> Fixes communication to commander

addons/sourcemod/scripting/include/autoexecconfig.inc, addons/sourcemod/scripting/include/sourcebans.inc, addons/sourcemod/scripting/nd_bot_features.sp, addons/sourcemod/scripting/nd_continents.sp, addons/sourcemod/scripting/sourcebans.sp, addons/sourcemod/scripting/sourcecomms.sp, addons/sourcemod/scripting/votemute_p.sp
removed compiler warnings for SM1.13
removed some extra spaces, tabs and break lines
removed "Yarr!" comment
standardized begining of comments with space
added/moved "#pragma semicolon 1" to beginning of some files
added/moved "#pragma newdecls required" to beginning of some files
(only from related modified files)
=> update support for SM1.13
