stickz/Redstone

.gitignore, updater/nd_player_warnings/translations/de/nd_player_warnings.phrases.txt, updater/nd_welcome/translations/cze/nd_welcome.phrases.txt, updater/nd_welcome/translations/de/nd_welcome.phrases.txt, updater/nd_welcome/translations/fr/nd_welcome.phrases.txt, updater/nd_welcome/translations/nd_welcome.phrases.txt, updater/nd_welcome/translations/nl/nd_welcome.phrases.txt
This pull request adds a german translation for your "Player Warnings" plugin, splits the phrases for the welcome plugin into multiple files (fr needs some rework) and adds a better translation for the "welcome" phrase.
=> Language update

addons/sourcemod/scripting/nd_player_warnings.sp, addons/sourcemod/scripting/nd_welcome.sp, updater/nd_player_warnings/nd_player_warnings.txt, updater/nd_welcome/nd_welcome.txt
=> Trigger Server Update

addons/sourcemod/scripting/nd_continents.sp, addons/sourcemod/scripting/nd_disconnect.sp, addons/sourcemod/scripting/nd_unit_limit.sp, addons/sourcemod/scripting/structminigame.sp, updater/nd_translation_updater/nd_translation_updater.txt, updater/nd_unit_limit/translations/nd_unit_limit.phrases.txt, updater/structminigame/structminigame.txt, updater/structminigame/translations/structminigame.phrases.txt
- Add Translation support to countless different plugins and missing phrases.
- Update the Translation Auto-Updater with the latest phrase links
- Overhaul structminigame plugin with full translation support and cleaner coding
- Improved multiple translation messages on the unit-limiter.
- Bump structminigame and translation_updater versions to trigger an update.
=> Trans. Support Plugin Updates!

addons/sourcemod/scripting/nd_translation_updater.sp
- This is simply to test the auto-builder.
=> Test Auto-Build

addons/sourcemod/scripting/nd_translation_updater.sp
- This is to test the auto-build feature.
=> Test Auto-Build #2

addons/sourcemod/scripting/nd_translation_updater.sp, updater/nd_translation_updater/nd_translation_updater.txt
- Update translations with latest Russian phrases
- See if the auto-build script works
=> Trigger Translation Update

addons/sourcemod/scripting/nd_build_shadow_fix.sp, addons/sourcemod/scripting/nd_deadweights.sp, addons/sourcemod/scripting/nd_offmap_fixes.sp, addons/sourcemod/scripting/nd_player_warnings.sp, addons/sourcemod/scripting/nd_superlogs.sp, addons/sourcemod/scripting/nd_translation_updater.sp, addons/sourcemod/scripting/nd_unit_limit.sp, addons/sourcemod/scripting/nd_welcome.sp, addons/sourcemod/scripting/structminigame.sp, updater/nd_build_shadow_fix/nd_build_shadow_fix.txt, updater/nd_deadweights/nd_deadweights.txt, updater/nd_offmap_fixes/nd_offmap_fixes.txt, updater/nd_player_warnings/nd_player_warnings.txt, updater/nd_superlogs/nd_superlogs.txt, updater/nd_translation_updater/nd_translation_updater.txt, updater/nd_unit_limit/nd_unit_limit.txt, updater/nd_welcome/nd_welcome.txt, updater/structminigame/structminigame.txt
- Update urls to point to the builder branch (automatic updating on commit)
- Bump versions to trigger a server update (needed to push new pointer)
=> Change Updater Links & Bump Versions

build_scripts/compile.sh
This build will fail, but that's not because of this PR but rather because of commit 59037d0100b6962cd7ae231dd73e2a0f553ba428 which should be reverted and retried again after this PR is merged
=> Exit build script with error if any command failed fix #44

addons/sourcemod/scripting/nd_unit_limit.sp, updater/nd_unit_limit/nd_unit_limit.txt
- This wasn't caught by Travis due to a glitch with the build passing.
=> Fix Plugin Error

updater/nd_translation_updater/translations/ru/nd_commander_restrictions.phrases.txt, updater/nd_translation_updater/translations/ru/nd_map_management.phrases.txt, updater/nd_translation_updater/translations/ru/nd_team_balancer.phrases.txt, updater/nd_translation_updater/translations/ru/nd_timelimit.phrases.txt, updater/structminigame/translations/ru/structminigame.phrases.txt
Translated following modules:
[nd_commander_restrictions](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/ru/nd_commander_restrictions.phrases.txt)
[nd_map_management](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/ru/nd_map_management.phrases.txt)
[nd_team_balancer](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/ru/nd_team_balancer.phrases.txt)
[nd_timelimit](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/ru/nd_timelimit.phrases.txt)
[structminigame](https://github.com/stickz/Redstone/blob/master/updater/structminigame/translations/ru/structminigame.phrases.txt)
=> Translate into russian

.travis.yml
Attempt to fix build feature not working.
Reverts stickz/Redstone#59
=> Revert "Simplify Travis CI deployment"

addons/sourcemod/scripting/dontshout.sp, addons/sourcemod/scripting/gameme.sp, addons/sourcemod/scripting/include/smlib/effects.inc, addons/sourcemod/scripting/nd_ping.sp, addons/sourcemod/scripting/nd_unit_limit.sp, addons/sourcemod/scripting/showdamage.sp
Remove FCVAR_PLUGIN flag which is depreciated in newer builds.
=> Fix development build issues

addons/sourcemod/scripting/ban_disconnected.sp, addons/sourcemod/scripting/dontshout.sp, addons/sourcemod/scripting/nd_deadweights.sp, addons/sourcemod/scripting/nd_disconnect.sp, addons/sourcemod/scripting/nd_offmap_fixes.sp, addons/sourcemod/scripting/nd_ping.sp, addons/sourcemod/scripting/nd_player_warnings.sp, addons/sourcemod/scripting/nd_translation_updater.sp, addons/sourcemod/scripting/nd_unit_limit.sp, addons/sourcemod/scripting/showdamage.sp, addons/sourcemod/scripting/structminigame.sp
- Change plugins so the smx files build and push properly.
=> Fix Updater Looping

addons/sourcemod/scripting/ban_disconnected.sp, addons/sourcemod/scripting/dontshout.sp, addons/sourcemod/scripting/nd_deadweights.sp, addons/sourcemod/scripting/nd_disconnect.sp, addons/sourcemod/scripting/nd_offmap_fixes.sp, addons/sourcemod/scripting/nd_ping.sp, addons/sourcemod/scripting/nd_player_warnings.sp, addons/sourcemod/scripting/nd_translation_updater.sp, addons/sourcemod/scripting/nd_unit_limit.sp, addons/sourcemod/scripting/showdamage.sp, addons/sourcemod/scripting/structminigame.sp
Reverts stickz/Redstone#70
Attempt to fix updater looping again. This simply recompiles all plugins.
=> Revert "Fix Updater Looping"

build_scripts/build.sh
=> Fix updater loop + mark builds as failed if compilation produces errors

addons/sourcemod/scripting/ban_disconnected.sp, addons/sourcemod/scripting/dontshout.sp, addons/sourcemod/scripting/nd_deadweights.sp, addons/sourcemod/scripting/nd_disconnect.sp, addons/sourcemod/scripting/nd_offmap_fixes.sp, addons/sourcemod/scripting/nd_ping.sp, addons/sourcemod/scripting/nd_player_warnings.sp, addons/sourcemod/scripting/nd_translation_updater.sp, addons/sourcemod/scripting/nd_unit_limit.sp, addons/sourcemod/scripting/showdamage.sp, addons/sourcemod/scripting/structminigame.sp
Restores stickz/Redstone#72
- Simply trigger a rebuild of plugins effected by a previous updater issue.
=> Restore "Fix Updater Looping""

addons/sourcemod/scripting/votemute_p.sp, updater/votemute_p/translations/ru/votemute_p.phrases.txt, updater/votemute_p/translations/votemute_p.phrases.txt
- Add translation support to many phrases.
- Proceduralize repetitive tasks using a Boolean function.
- Trim delay communicating to seconds only.
=> Improve votemute

addons/sourcemod/scripting/nd_unit_limit.sp, updater/nd_unit_limit/translations/nd_unit_limit.phrases.txt
- Notify team with translation support when a limit is set.
=> Improve Unit Limit Plugin

addons/sourcemod/scripting/include/nd_rounds.inc, addons/sourcemod/scripting/nd_round_engine.sp
Add a new ND_RoundEnded() native to the engine.
=> Improve Round Engine

addons/sourcemod/scripting/nd_project_communication/building_requests.sp, updater/nd_project_communication/translations/de/nd_project_communication.phrases.txt, updater/nd_project_communication/translations/nd_project_communication.phrases.txt, updater/nd_project_communication/translations/ru/nd_project_communication.phrases.txt
- Add 'Extended Building Request' feature
- Update for Russian and German translations
=> Improve Building Requests

addons/sourcemod/scripting/nd_ontakedamage_fix.sp
- Add class refresh feature
- Remove damage sparse
=> Improve ontakedamage fix

addons/sourcemod/scripting/nd_ontakedamage_fix.sp
- Removed unneeded join class listener
- Change class reset to class refresh
=> Improve nd_ontakedamage_fix

addons/sourcemod/scripting/nd_stats_retrieval.sp
- Add redundancy in-case the first check fails.
- Make code more abstract for future updates.
=> Improve nd_stats_retrieval

addons/sourcemod/scripting/nd_rockthevote.sp
- Enhance client count calculation using the new RED native
- Convert a lot of things to transitional syntax
- Add newdecls required to a large portion of the plugin
=> Improve nd_rockthevote plugin

addons/sourcemod/scripting/nd_com_engine.sp
- Add copyright, plugin info and updater support
=> Improve nd_com_engine

addons/sourcemod/scripting/nd_universal_translator.sp, addons/sourcemod/scripting/ndpc/commander_lang.sp
- Use the new commander engine instead of the old commander plugin
=> Improve universal translator

addons/sourcemod/scripting/nd_translation_updater.sp
check for plugin updates at round end (moved from TB plugin)
=> Improve translation updater

addons/sourcemod/scripting/nd_universal_translator.sp, addons/sourcemod/scripting/ndpc/building_requests.sp, addons/sourcemod/scripting/ndpc/stock_functions.sp
=> Add building aliases to translator

addons/sourcemod/scripting/nd_universal_translator.sp, addons/sourcemod/scripting/ndpc/building_requests.sp
- Attempt to fix logging issue
- Add assembler phrase
=> Improve translation plugin

game_scripts/weapons/weapon_paladin.txt, game_scripts/weapons/weapon_psg.txt
Adjusted base exo damage multiplier on paladin and psg from `2.0 to 2.1`.
=> Increase sniper damage to exos by 10%

addons/sourcemod/scripting/nd_surrender.sp
- Fix spacing
- Remove un-needed veto step
- Use majority if the commander hasn't already voted.
=> Assume veto if commander hasn't voted

addons/sourcemod/scripting/nd_bot_features.sp
Fixed a bug causing server slots not to be restored properly.
Fixed a bug causing empty team slots not to be filled properly.
=> Improve fill quota algorithm

addons/sourcemod/scripting/nd_bot_feat/modulus_quota.sp, addons/sourcemod/scripting/nd_bot_features.sp
=> Revert "Reduce bot counts on clocktower"

addons/sourcemod/scripting/nd_player_warnings.sp
- Abstract TargetFound() and PrintWarning() function
=> Improve nd_player_warnings plugin

addons/sourcemod/scripting/nd_damage_mult.sp
Update convar creation to fix indexing issues with plugin convars.
=> Fix-up damage multiplier plugin

addons/sourcemod/scripting/include/nd_structures.inc, addons/sourcemod/scripting/nd_damage/convars.sp, addons/sourcemod/scripting/nd_damage/damage_events.sp, addons/sourcemod/scripting/nd_damage_mult.sp
- Add radar, power station and armory - RED damage multipliers
=> Improve damage multiplier plugin

addons/sourcemod/scripting/nd_rockthevote.sp
- Add a ConVar to support map change votes after the timeout, but a higher percentage requirement.
- Remove broken feature intended for lower player count enabling of RTV.
- Optimize checkForPass() and StartRTVDisableTimer() functions.
- Add additional commenting to explain plugin code.
=> Improve and Fix RTV Plugin

addons/sourcemod/scripting/nd_rockthevote.sp, addons/sourcemod/scripting/nd_warmup.sp
This feature set is designed for RTVing without round start. It's useful for team-pick events.
=> Improve RTV plugin

addons/sourcemod/scripting/nd_universal_translator.sp, addons/sourcemod/scripting/ndpc/features/team_lang.sp
- Using the wrong constant to declare command.
=> Fix translator bug

addons/sourcemod/scripting/include/nd_rounds.inc, addons/sourcemod/scripting/include/nd_structures.inc, addons/sourcemod/scripting/nd_damage_mult.sp, addons/sourcemod/scripting/nd_round_engine.sp, addons/sourcemod/scripting/nd_team_breakdown.sp
- Add ND_RoundStartedThisMap() native boolean.
- Add ND_OnRoundEndedEX() forward.
- Fix damage multiplier sdk hooks.
=> Improve round engine & fix hooks

addons/sourcemod/scripting/nd_rockthevote.sp
- Percentage before and after timeout for popular and unpopular maps.
=> Improve RTV with four pass percentages

addons/sourcemod/scripting/gameme.sp, updater/gameme/translations/da/gameme.phrases.txt
- Fix a bug with session hpk not working properly.
- Fix the insurgency events.
- Add danish translation support.
=> Roll-out 2017/10/25 GameME version

addons/sourcemod/scripting/nd_com_check/clientprefs.sp, addons/sourcemod/scripting/nd_commander_checklist.sp, updater/nd_commander_checklist/translations/sm_comm_checklist.phrases.txt
- Use the client language instead of server language for translations
- Add clientprefs support to toggle the feature on/off.
- User timer instead of update events for more control
=> Fix commander checklist plugin

addons/sourcemod/scripting/mapchooser.sp
- Add client prefs support.
- Add updater support.
- Add voter messages.
=> Improve mapchooser plugin

addons/sourcemod/scripting/include/nd_maps.inc
Use new style declarations. Put back sk_metro.
=> Fix nd_maps.inc

addons/sourcemod/scripting/include/nd_maps.inc, addons/sourcemod/scripting/nd_bot_features.sp
- Array out of bounds due to sk_metro missing from stock map list
=> Fix nd_bot_features

addons/sourcemod/scripting/nd_commander_demote.sp
- Round votes to nearest instead of floor.
- Don't require a minimum number of team players to demote.
- Require 60% instead of 51% to demote a veteran commander.
=> Improve commander demote plugin

addons/sourcemod/scripting/include/nd_research.inc, addons/sourcemod/scripting/nd_research_engine.sp
- Research starts at one not zero for some reason.
=> Fix research enumeration

addons/sourcemod/scripting/nd_resource_spawner.sp
Added four more tetriaties to the map.
=> Additional tetriatries for nd_submarine

addons/sourcemod/scripting/include/nd_struct_eng.inc, addons/sourcemod/scripting/nd_damage_mult.sp, addons/sourcemod/scripting/nd_offmap_fixes.sp, addons/sourcemod/scripting/nd_structure_engine.sp
- Add ND_OnStructureCreated() forward.
- Implement in offmap fixes and damage multipliers.
=> Improve structure engine

addons/sourcemod/scripting/nd_resource_spawner.sp
- Remove and respawn four tertiary resource points on Rock.
- Create a tiered array system for handling multiple map respawns.
=> Improve resource spawner

addons/sourcemod/scripting/nd_map_thresholds.sp, addons/sourcemod/scripting/nd_resource_spawner.sp, addons/sourcemod/scripting/nd_server_type.sp
- Set resource changes to beta server only
- Control map voter changes based on resource changes.
- Renable Rew's submarine points on test server
=> Implement nd_server_type controls

addons/sourcemod/scripting/include/nd_classes.inc, addons/sourcemod/scripting/include/nd_print.inc, addons/sourcemod/scripting/nd_player_speed.sp, updater/nd_player_speed/translations/nd_player_speed.phrases.txt
- Fix bugs with nd_player_speed printouts
- Increase exo movement speed by 1% per infantry boost level.
=> Improve nd_player_speed plugin

addons/sourcemod/scripting/nd_bot_feat/modulus_quota.sp, addons/sourcemod/scripting/nd_bot_features.sp
- Fix turret bot quota reduction algorithm to work properly.
- Fix multiple possible bugs causing uneven bot counts
=> Multiple bot-features fixes

addons/sourcemod/scripting/include/nd_rstart.inc, addons/sourcemod/scripting/include/nd_stocks.inc, addons/sourcemod/scripting/include/nd_teampick.inc, addons/sourcemod/scripting/nd_commander_actions.sp
- Only allow certain commands like commander actions, to be used if the team-pick successfully runs.
=> Implement Team Pick run only access

addons/sourcemod/scripting/nd_tools.sp
- These were moved to a separate nd_sucide_controls plugin.
=> Remove suicide controls from nd_tools

addons/sourcemod/scripting/nd_round_start.sp, addons/sourcemod/scripting/nd_rstart/restart.sp
- Add !RestartWarmup command to nd_rstart
- Don't allow the round to be restarted, unless it's actually started
- Set time limit to unlimited, to pass control back to other plugins.
=> Improve round restart logic

addons/sourcemod/scripting/nd_damage/convars.sp, addons/sourcemod/scripting/nd_damage/damage_events.sp, addons/sourcemod/scripting/nd_damage_mult.sp
=> Revert "Fix Structure Damage Exploit"

build_scripts/build.sh
- Remove pre-created updater folder requirement to build server plugins.
- Delete all the plugin folders which do not house server translations. (not required)
=> Remove updater folder requirement to build plugins

build_scripts/build.sh
=> Revert "Remove updater folder requirement to build plugins"

addons/sourcemod/scripting/nd_swgm.sp
- Also cleanup some code to make it more readable.
=> Use autoexecconfig() wrapper for nd_swgm

addons/sourcemod/scripting/nd_grenade_trails_deux.sp, addons/sourcemod/scripting/nd_trails/clientprefs.sp
- Required to enforce steam group join requirements.
=> Change grenade trail default to off

addons/sourcemod/scripting/nd_bot_features.sp
=> Revert "Add 2 bots (instead of 1) for every missing player"

addons/sourcemod/scripting/include/nd_com_eng.inc, addons/sourcemod/scripting/include/nd_struct_eng.inc, addons/sourcemod/scripting/nd_com_engine.sp, addons/sourcemod/scripting/nd_commander_demote.sp, addons/sourcemod/scripting/nd_structure_engine.sp
- Auto-detect and demote commanders for not building a structure after 150s.
- Don't start commander chair entrance demote until both teams have a commander.
- Improve commander and structure engine for additional future functionality.
- Use autoexecconfig wrapper for convar creation on nd_commander_demote.
=> Improve Commander Features

addons/sourcemod/scripting/include/nd_spec.inc, addons/sourcemod/scripting/nd_bot_features.sp, addons/sourcemod/scripting/nd_spectators.sp
- Create ND_OnPlayerLockSpec() and ND_OnPlayerLockSpecPost() forwards
- Refresh bot count after a player locks into spectator.
=> Improve Spectator Features

addons/sourcemod/scripting/nd_commander_chair.sp
- Add both an OnTeamCount() and TotalPlayerCount() for the chair block threshold.
- Apply the new threshold to both commander elections and commander chair blocking.
=> Improve Chair Block Feature

addons/sourcemod/scripting/include/nd_print.inc, addons/sourcemod/scripting/nd_commander_chair.sp
- Create PrintMessageCom() wrapper in nd_print.inc to cleanup the nd_commander_chair plugin.
=> Improve Commander Printing

addons/sourcemod/scripting/nd_bot_features.sp
- Fill bots exponentially instead of linear to better reflect the situation.
=> Improve Bot Features

addons/sourcemod/scripting/nd_bot_features.sp
- Reduce bot filler quota based on the number of spectators.
- Resolves bug with bots not filling properly when there's too many spectators.
=> Fix Bot Features

addons/sourcemod/scripting/nd_bot_feat/commands.sp, addons/sourcemod/scripting/nd_bot_features.sp
=> Revert "Fix Bot Features"

addons/sourcemod/scripting/nd_commander_demote.sp
- Resolve array indexing issue when commander is demoted and disconnects.
- Resolve expected float but received integer, when calculating minimum demote percentage.
=> Fix commander demote plugin

addons/sourcemod/scripting/nd_surrender.sp
- Raise team pick surrender percentage from 51% to 60%.
- Add AutoExecConfig ConVar support for surrender plugin.
=> Improve Surrender Plugin

addons/sourcemod/scripting/nd_grenade_trails_deux.sp
OnMapStart() is called when a plugin reloads
=> Remove late loading support

addons/sourcemod/scripting/nd_damage/convars.sp, addons/sourcemod/scripting/nd_damage/damage_events.sp, addons/sourcemod/scripting/nd_damage_mult.sp, updater/nd_damage_mult/translations/nd_damage_mult.phrases.txt
* Added BBQ 3%, 5%, 7% infantry boost damage increases.
* Added structure reinforcement 5%, 10%, 15% artillery protection.
=> Improve damage multipliers

addons/sourcemod/scripting/include/nd_print.inc, addons/sourcemod/scripting/nd_player_speed.sp, updater/nd_player_speed/translations/nd_player_speed.phrases.txt
* Added grenadier speed increases of 1% per infantry boost level.
* Cleaned up console outputs of movement speed increases.
* Restructured code to function better with more changes.
=> Grenadier IB speed increases & Restructure Code

updater/nd_player_tips/nd_player_tips.phrases.txt
=> Add 5 tips for nd_player_tips

updater/nd_player_tips/translations/nd_player_tips.phrases.txt
To help understand each item, i have tried to comment / explain them. 
Also if Vertex could update them as to how they are actually / would be implemented to aid in understanding and hopefully lead to other options. This would not need to be detailed, but to give a better idea of what is actually going to be the trigger for each. For example, on the Grenade Spam, update it with maybe how 'quick succession' is going to be defined in implementation (2 grenades in 2 seconds).
=> Added comments to each player tip

updater/nd_player_tips/translations/nd_player_tips.phrases.txt
Added "Captured Resource" to show information on the last resource point captured.
=> Added captured resource player tip phrases

addons/sourcemod/scripting/nd_team_balancer_v5.sp
- Require three players to place by skill.
- Fix a bug causing one extra skill placements not to work properly.
- Add AutoExecConfig support to update the convar file.
=> Improve team balancer

updater/nd_commander_tips/translations/nd_commander_tips.phrases.txt
I have numbered them in the comments (to keep count / track) and added comments as i went along.
=> Added the first 10 tips to the file

updater/nd_commander_tips/translations/nd_commander_tips.phrases.txt
Re-Numbered after some removals and added the last few, now up to 23.
=> Re-Numbered and added the last few

addons/sourcemod/scripting/nd_commander_tips.sp
He was quite involved in the brainstorming
=> Added Shir to the authors list

server_configs/redstone/bot_profiles_shakespearean
Changed the names of the Elite and Experts to ones from Shakespeare.
=> Change bot names to Shakespearean theme

addons/sourcemod/scripting/nd_offmap_fixes.sp
This pull request disables building off map near con base on hydro
=> disable building of cons base

addons/sourcemod/gamedata/build-structure.games.txt
- Fixes Windows signature for CNDPlayer::Commander_BuildStructure
- Fixes Windows signature for CNDPlayer::Commander_BuildEmergencyAssembler
- Changes mystery variable in functions to correct name
=> Fixing Structure Building Gamedata

addons/sourcemod/scripting/include/nd_classes.inc
- Creates enum and stock so using plugins can check a class with a single function rather than two (one for class type + one for sub class)
- Adds stock ND_GetCountInClass
- Adds stock ND_GetNearbyTeammateInClass
- Adds stock ND_GetPlayerClass
=> Adds features to nd_classes

addons/sourcemod/scripting/nd_discord_playerlist.sp
Adds a plugin that outputs the list of players on the server to a file that the Discord bot can read.
=> Add Discord Player List plugin

addons/sourcemod/scripting/include/nd_classes.inc, addons/sourcemod/scripting/nd_bot_radio_helpers.sp
Adds bot functionality to listen and respond by dropping a medkit or ammopack when a teammate calls for a medic or supplies using the built- in ND radio commands
=> Bots now drop medkits & ammopacks when called

.github/workflows/pull.yml
Adds support for building the development branch of sourcemod.
=> Improve pull request testing

addons/sourcemod/scripting/nd_breakdown/clientprefs.sp, addons/sourcemod/scripting/nd_com_ban/text_files.sp, addons/sourcemod/scripting/nd_com_dep/text_files.sp, addons/sourcemod/scripting/nd_grenade_trails_deux.sp, addons/sourcemod/scripting/nd_weight/text_files.sp, addons/sourcemod/scripting/ndpc/phrases/capture.sp, addons/sourcemod/scripting/ndpc/phrases/research.sp, addons/sourcemod/scripting/ndpc/stock_functions.sp
Fixes compilation warnings against SM1.12
except for the gameme.sp file
=> Fixes compilation warnings against SM1.12

addons/sourcemod/scripting/defaultmap.sp, addons/sourcemod/scripting/nd_entity_engine.sp, addons/sourcemod/scripting/nd_map_management_v2.sp, addons/sourcemod/scripting/nd_resource_depletion.sp, addons/sourcemod/scripting/nd_resource_engine.sp, addons/sourcemod/scripting/nd_resource_trickle.sp
=> Fix warnings and log errors
